version: '3.4'

x-services:
  app_base: &app_base
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    environment:
      - RAILS_ENV=production
      - REDIS_URL=
      - DATABASE_URL=
      - SECRET_KEY_BASE=1213
    volumes:
      - .:/srv/app
      - /srv/app/vendor/bundle
      - /srv/app/public
    tmpfs:
      - /srv/app/tmp
      - /srv/app/tmp/pids
      - /srv/app/tmp/sockets
      - /srv/app/tmp/cache
    entrypoint: "./docker-entrypoint.sh"

services:
  app:
    <<: *app_base
    command: bundle exec puma
    ports:
      - "3000:3000"

  worker:
    <<: *app_base
    command: bundle exec sidekiq

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
