version: '3.4'

x-services:
  app_base: &app_base
    build:
      context: .
      dockerfile: ./docker/rails/DockerFile
    environment:
      - REDIS_URL=redis://redis_sidekiq_master:6379/0
      - POSTGRES_URL=
    volumes:
      - .:/srv/app
      - /srv/app/vendor/bundle
      - /srv/app/public
    entrypoint: "./deploy/docker-entrypoint-app.sh"

services:
  rails_server:
    <<: *app_base
    command: bundle exec puma
    ports:
      - "3000:3000"

  rails_worker:
    <<: *app_base
    command: bundle exec sidekiq

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/DockerFile
    depends_on:
      - rails_server
    ports:
      - 80:80

volumes:
  postgres-data:
  elasticsearch-data:
  minio-data:

