default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= Rails.application.class.parent_name.underscore %>_development

test:
  <<: *default
  database: <%= Rails.application.class.parent_name.underscore %>_test

production:
  url: <%= ENV["DATABASE_URL"] %>